version: 2.1

orbs:
  node: circleci/node@4.6.0

jobs:
  build:
    working_directory: ~/code-20210808-yogitabhatia/
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          app-dir: ~/code-20210808-yogitabhatia/server/
          cache-path: node_modules
          override-ci-command: npm i
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
